// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7bVPpAY4aSQd2skmUgI63mU5cD9_FtPs',
    appId: '1:987714689172:web:c7b649899954aa17347c81',
    messagingSenderId: '987714689172',
    projectId: 'flutter-smit-1d781',
    authDomain: 'flutter-smit-1d781.firebaseapp.com',
    storageBucket: 'flutter-smit-1d781.appspot.com',
    measurementId: 'G-16EDPJ1PEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACPyWzJdBkA5FL3Pz5JG3-LVijeWZKA4Q',
    appId: '1:987714689172:android:bcfed04c6c7558e7347c81',
    messagingSenderId: '987714689172',
    projectId: 'flutter-smit-1d781',
    storageBucket: 'flutter-smit-1d781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RwGT6tBV7CoAVKGfsRCIqVH9rxPK7Kc',
    appId: '1:987714689172:ios:52a9d47e1e7de3de347c81',
    messagingSenderId: '987714689172',
    projectId: 'flutter-smit-1d781',
    storageBucket: 'flutter-smit-1d781.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RwGT6tBV7CoAVKGfsRCIqVH9rxPK7Kc',
    appId: '1:987714689172:ios:52a9d47e1e7de3de347c81',
    messagingSenderId: '987714689172',
    projectId: 'flutter-smit-1d781',
    storageBucket: 'flutter-smit-1d781.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7bVPpAY4aSQd2skmUgI63mU5cD9_FtPs',
    appId: '1:987714689172:web:c4a0c5ede79cdcc8347c81',
    messagingSenderId: '987714689172',
    projectId: 'flutter-smit-1d781',
    authDomain: 'flutter-smit-1d781.firebaseapp.com',
    storageBucket: 'flutter-smit-1d781.appspot.com',
    measurementId: 'G-MEE46HP8VX',
  );
}
